clear;
clc;
close all;

data = load('../results/brain_activity.mat');

positions = data.positions;
edges = data.edges;
groups = data.groups;
activity = data.activity;

g = groups == 0;
s = groups == 1;

figure('Color','w');

for t = 1:size(activity,1)

    clf;
    hold on;

    for i = 1:size(edges,1)

        a = edges(i,1) + 1;
        b = edges(i,2) + 1;

        plot3(...
            [positions(a,1) positions(b,1)], ...
            [positions(a,2) positions(b,2)], ...
            [positions(a,3) positions(b,3)], ...
            'Color',[0.75 0.75 0.75], ...
            'LineWidth',0.2 ...
        );
    end

    node_activity = activity(t,:);

    node_size = 20 + 100 * ...
        (node_activity ./ ...
        (max(node_activity) + eps));

    scatter3(...
        positions(g,1), ...
        positions(g,2), ...
        positions(g,3), ...
        node_size(g), ...
        node_activity(g), ...
        'filled' ...
    );

    scatter3(...
        positions(s,1), ...
        positions(s,2), ...
        positions(s,3), ...
        node_size(s), ...
        node_activity(s), ...
        'filled' ...
    );

    xlabel('X');
    ylabel('Y');
    zlabel('Z');

    title(...
        sprintf(...
        '100B-Neuron-Equivalent Brain | Time %d / %d', ...
        t, ...
        size(activity,1)) ...
    );

    axis equal;
    grid on;
    view(3);
    colorbar;

    drawnow;
    pause(0.08);

end

rotate3d on;
hold off;
