clear;
clc;
close all;

data = load('../results/brain_graph.mat');

positions = data.positions;
edges = data.edges;
groups = data.groups;

figure('Color','w');
hold on;

for i = 1:size(edges,1)
    a = edges(i,1) + 1;
    b = edges(i,2) + 1;

    plot3(...
        [positions(a,1) positions(b,1)], ...
        [positions(a,2) positions(b,2)], ...
        [positions(a,3) positions(b,3)] ...
    );
end

g = groups == 0;
s = groups == 1;

scatter3(...
    positions(g,1), ...
    positions(g,2), ...
    positions(g,3), ...
    45, ...
    'filled' ...
);

scatter3(...
    positions(s,1), ...
    positions(s,2), ...
    positions(s,3), ...
    45, ...
    'filled' ...
);

xlabel('X');
ylabel('Y');
zlabel('Z');

title('100B-Neuron-Equivalent Cognitive Brain');

legend(...
    'Connections', ...
    'General System (G)', ...
    'Specific System (S)' ...
);

axis equal;
grid on;
view(3);
rotate3d on;

hold off;
