clear
clc
close all

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));

brainFile = fullfile(projectRoot,'results','matlab_multiscale_brain.mat');
surfaceFile = fullfile(projectRoot,'third_party','BrainNet-Viewer','Data','SurfTemplate','BrainMesh_ICBM152.nv');

data = load(brainFile);
brain = data.brain;

[vertices,faces] = read_nv_surface(surfaceFile);

P = brain.population.position;
factor = brain.population.factor;
hemisphere = brain.population.hemisphere;
A = brain.connectivity.A;

vmin = min(vertices,[],1);
vmax = max(vertices,[],1);

pmin = min(P,[],1);
pmax = max(P,[],1);

Pnorm = (P - pmin) ./ max(pmax - pmin,eps);
MNIpositions = vmin + Pnorm .* (vmax - vmin);

left = hemisphere == "L";
right = hemisphere == "R";
G = factor == "G";
S = factor == "S";

MNIpositions(:,1) = abs(MNIpositions(:,1));
MNIpositions(left,1) = -MNIpositions(left,1);

MNIpositions(:,2) = max(min(MNIpositions(:,2),vmax(2)),vmin(2));
MNIpositions(:,3) = max(min(MNIpositions(:,3),vmax(3)),vmin(3));

figureHandle = figure( ...
    'Color',[0.015 0.018 0.025], ...
    'Name','100B-Neuron-Equivalent Cognitive Brain', ...
    'NumberTitle','off', ...
    'Renderer','opengl', ...
    'Position',[100 70 1500 900]);

axesHandle = axes('Parent',figureHandle);

hold(axesHandle,'on');
axis(axesHandle,'equal');
axis(axesHandle,'vis3d');
axis(axesHandle,'off');
view(axesHandle,3);

brainSurface = patch( ...
    'Parent',axesHandle, ...
    'Vertices',vertices, ...
    'Faces',faces, ...
    'FaceColor',[0.65 0.70 0.78], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.18, ...
    'AmbientStrength',0.35, ...
    'DiffuseStrength',0.65, ...
    'SpecularStrength',0.20);

material(axesHandle,'dull');

camlight(axesHandle,'headlight');
camlight(axesHandle,'right');
lighting(axesHandle,'gouraud');

sameX = [];
sameY = [];
sameZ = [];

crossX = [];
crossY = [];
crossZ = [];

for i = 1:size(A,1)
    for j = i+1:size(A,2)

        if A(i,j) <= 0
            continue
        end

        if hemisphere(i) == hemisphere(j)

            sameX = [sameX;MNIpositions(i,1);MNIpositions(j,1);NaN];
            sameY = [sameY;MNIpositions(i,2);MNIpositions(j,2);NaN];
            sameZ = [sameZ;MNIpositions(i,3);MNIpositions(j,3);NaN];

        else

            crossX = [crossX;MNIpositions(i,1);MNIpositions(j,1);NaN];
            crossY = [crossY;MNIpositions(i,2);MNIpositions(j,2);NaN];
            crossZ = [crossZ;MNIpositions(i,3);MNIpositions(j,3);NaN];

        end

    end
end

sameEdges = plot3( ...
    axesHandle, ...
    sameX, ...
    sameY, ...
    sameZ, ...
    'Color',[0.35 0.42 0.55], ...
    'LineWidth',0.55);

crossEdges = plot3( ...
    axesHandle, ...
    crossX, ...
    crossY, ...
    crossZ, ...
    'Color',[0.90 0.30 0.72], ...
    'LineWidth',0.9);

generalNodes = scatter3( ...
    axesHandle, ...
    MNIpositions(G,1), ...
    MNIpositions(G,2), ...
    MNIpositions(G,3), ...
    42, ...
    [0.10 0.75 1.00], ...
    'filled', ...
    'MarkerEdgeColor',[0.85 0.95 1.00], ...
    'LineWidth',0.35);

specificNodes = scatter3( ...
    axesHandle, ...
    MNIpositions(S,1), ...
    MNIpositions(S,2), ...
    MNIpositions(S,3), ...
    42, ...
    [1.00 0.38 0.12], ...
    'filled', ...
    'MarkerEdgeColor',[1.00 0.85 0.70], ...
    'LineWidth',0.35);

generalNodes.MarkerFaceAlpha = 0.9;
specificNodes.MarkerFaceAlpha = 0.9;

title( ...
    axesHandle, ...
    sprintf('100B-NEURON-EQUIVALENT COGNITIVE BRAIN\n200 populations | 100 G | 100 S | 842 structural edges'), ...
    'Color','w', ...
    'FontSize',16, ...
    'FontWeight','bold');

infoText = sprintf( ...
    ['COMPUTATIONAL BRAIN\n' ...
     'Equivalent neurons: 100B\n' ...
     'Populations: 200\n' ...
     'G system: 100\n' ...
     'S system: 100\n' ...
     'Structural edges: 842\n\n' ...
     'Blue = G\n' ...
     'Orange = S\n' ...
     'Pink = interhemispheric'], ...
    brain.scale.equivalent_neurons / 1e9);

annotation( ...
    figureHandle, ...
    'textbox', ...
    [0.02 0.68 0.19 0.25], ...
    'String',infoText, ...
    'Color','w', ...
    'FontSize',10, ...
    'BackgroundColor',[0.02 0.025 0.035], ...
    'EdgeColor',[0.25 0.32 0.42], ...
    'FitBoxToText','on');

uicontrol( ...
    'Parent',figureHandle, ...
    'Style','pushbutton', ...
    'String','Toggle Connections', ...
    'Units','normalized', ...
    'Position',[0.82 0.92 0.15 0.04], ...
    'Callback',@(src,event)toggleVisibility([sameEdges crossEdges]));

uicontrol( ...
    'Parent',figureHandle, ...
    'Style','pushbutton', ...
    'String','Toggle G', ...
    'Units','normalized', ...
    'Position',[0.82 0.87 0.07 0.04], ...
    'Callback',@(src,event)toggleVisibility(generalNodes));

uicontrol( ...
    'Parent',figureHandle, ...
    'Style','pushbutton', ...
    'String','Toggle S', ...
    'Units','normalized', ...
    'Position',[0.90 0.87 0.07 0.04], ...
    'Callback',@(src,event)toggleVisibility(specificNodes));

uicontrol( ...
    'Parent',figureHandle, ...
    'Style','pushbutton', ...
    'String','Surface', ...
    'Units','normalized', ...
    'Position',[0.82 0.82 0.07 0.04], ...
    'Callback',@(src,event)toggleVisibility(brainSurface));

uicontrol( ...
    'Parent',figureHandle, ...
    'Style','pushbutton', ...
    'String','Reset View', ...
    'Units','normalized', ...
    'Position',[0.90 0.82 0.07 0.04], ...
    'Callback',@(src,event)resetView(axesHandle));

rotate3d(figureHandle,'on');

zoom(figureHandle,'on');

pan(figureHandle,'on');

fprintf('\n');
fprintf('INTERACTIVE 3D BRAIN READY\n');
fprintf('Surface vertices: %d\n',size(vertices,1));
fprintf('Surface triangles: %d\n',size(faces,1));
fprintf('Populations: %d\n',size(MNIpositions,1));
fprintf('Equivalent neurons: %dB\n',round(brain.scale.equivalent_neurons/1e9));
fprintf('Structural edges: %d\n',nnz(A));
fprintf('\n');


function toggleVisibility(objects)

for k = 1:numel(objects)

    if strcmp(objects(k).Visible,'on')
        objects(k).Visible = 'off';
    else
        objects(k).Visible = 'on';
    end

end

end


function resetView(ax)

view(ax,3);
axis(ax,'equal');
axis(ax,'vis3d');

end
